export const getEmblem = team => {
  switch (team.toLowerCase()) {
    case "ari":
      return require("../logos/ari.png");
    case "atl":
      return require("../logos/atl.png");
    case "bal":
      return require("../logos/bal.png");
    case "buf":
      return require("../logos/buf.png");
    case "car":
      return require("../logos/car.png");
    case "chi":
      return require("../logos/car.png");
    case "cin":
      return require("../logos/cin.png");
    case "cle":
      return require("../logos/cle.png");
    case "dal":
      return require("../logos/dal.png");
    case "den":
      return require("../logos/den.png");
    case "det":
      return require("../logos/det.png");
    case "gb":
      return require("../logos/gb.png");
    case "hou":
      return require("../logos/hou.png");
    case "ind":
      return require("../logos/ind.png");
    case "jac":
      return require("../logos/jax.png");
    case "kc":
      return require("../logos/kc.png");
    case "la":
      return require("../logos/la.png");
    case "mia":
      return require("../logos/mia.png");
    case "min":
      return require("../logos/min.png");
    case "ne":
      return require("../logos/ne.png");
    case "no":
      return require("../logos/no.png");
    case "nyg":
      return require("../logos/nyg.png");
    case "nyj":
      return require("../logos/nyj.png");
    case "oak":
      return require("../logos/oak.png");
    case "phi":
      return require("../logos/phi.png");
    case "pit":
      return require("../logos/pit.png");
    case "sd":
      return require("../logos/sd.png");
    case "sea":
      return require("../logos/sea.png");
    case "sf":
      return require("../logos/sf.png");
    case "tb":
      return require("../logos/tb.png");
    case "ten":
      return require("../logos/ten.png");
    case "was":
      return require("../logos/was.png");
    default:
      return require("../logos/was.png");
  }
};
